---
- name: clone the golang git repo
  git:
    repo: "{{ gitsite }}golang/go"
    dest: "{{ gitpath }}go"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: build & install the latest golang
  shell: GOROOT_BOOTSTRAP={{ gobootstrap }} ./make.bash
  args:
    chdir: "{{ gitpath }}/go/src"
  when: git.before != git.after

- name: get some useful golang packages and tools
  command: go get -u {{ item }}
  items:
    - golang.org/x/tools/cmd/present
    - golang.org/x/tools/cmd/goimports
    - google.golang.org/grpc
    - github.com/golang/protobuf/protoc-gen-go
    - github.com/golang/mock/gomock
    - github.com/golang/mock/mockgen
    - github.com/kardianos/govendor
    - k8s.io/kubernetes/cmd/kubectl
    - github.com/coreos/etcd/cmd/etcd
    - github.com/coreos/etcd/cmd/etcdctl
    - github.com/github/hub
    - github.com/tianon/gosu
    - github.com/streadway/amqp
    - github.com/derekparker/delve/cmd/dlv
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
  when: git.before != git.after
